### ISSUE TITLE
support command.subcommand pattern

### ISSUE THREAD

**Issue by dominictarr** [fraction/ssb-cli#1]
A standalone cli installation is a good idea, because then you can have different distributions, and still use them with a CLI. I just want to recommend that you also support `command.subcommand` pattern, i.e. `query.read` it's just a small thing but then the usage documentations we already have still apply

**Comment by christianbundy** [comment]
Great idea, thanks for recommending it.

I've just added an [implementation here](https://github.com/fraction/ssb-cli/blob/ec1b3dccb11aa605fa24b54a7fe6ee377c690ffa/lib/replace-dot-commands.js#L1-L28) and added [tests here](https://github.com/fraction/ssb-cli/blob/master/test.js#L160-L192) and released it as v1.4.0. Could you confirm that this is working the way you'd expect?

**Comment by dominictarr** [comment]
that looks like it should work

**Comment by dominictarr** [comment]
we could use this for integration tests for new ssb implementations. a cli client is a good first step for a new implementation, it requires secret-handshake, and muxrpc, and should be able to talk to a js sbot... I started some tests a while back that you can drive with different clients: https://github.com/ssbc/ssb-integration-tests `sbotc` should also work, for example

**Comment by christianbundy** [comment]
Thanks for the tip, I'll look into that.
